# Generated by Django 5.2.13 on 2026-04-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="original_url",
            field=models.URLField(max_length=2048),
        ),
    ]
