# Generated by Django 5.2.13 on 2026-05-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0004_mod9_unique_preview_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="favicon",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
